# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e86cfb284d1a2411344e50eb5f930fdae6eb25bcc26525c3f9c65810b79345c287e9799169018dc3c3eee9ea7952d2d5ccbe856cf9285370931ebaee9c6e8b39

test:
  secret_key_base: c614f1b19e110815d4df8458fae607ab510fc9012cfc810b69036cbf0043b63e2ac0f72271aa5778ea6090e3ca1e00039a84be40c0fc7d9db3e154487dbb8ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
